### ISSUE TITLE
BUG: FMC using old airport name for generating routes

### ISSUE THREAD

**Issue by iiRevzz** [GeoFS-Extensions/autoland#87]
**Describe the bug**
Generate New Route route not updating the Arrival ICAO on the new route.

**To Reproduce**
Not exactly sure, I just know that I set it to KIMM, and finished the runways on that airport, and then generated route, then set Arrival to KOWX, and the new route that I generated did not have the new ICAO for arrival updated, just everything else was updated except for the Arrival.

**Expected behavior**
I expected it to update the arrival in the new generated route.

**Actual behavior**
It said KIMM, even though I updated it before I clicked Generate Route.

**Screenshots**
https://i.imgur.com/S5uuWhQ.png
https://i.imgur.com/Dl05Sak.png

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 94.0.4606.71

**Comment by nicolas377** [comment]
Sorry we haven't gotten to this! I'm busy with school, and we're working on the monorepo integration right now! I've ran into this in internal testing, so I can confirm this isn't a one-off. I'll try and track down where this bug is.

Technical details for future me:
This probably lies somewhere in the function that generates the fmc route. (ui/progress.ts?)

**Comment by Guy-Adler** [comment]
This is solved somewhere in #124 or #104.
